gitterToken: {{gitterToken}}
gitterRoomId: {{gitterRoomId}}
fromAddress: resumes@{{route53Record}}
recipients:
  - {{recipient}}
resumesBucket: {{resumesBucket}}
resumesMetaTable: {{resumesMetaTable}}
elastiCacheHost: {{elastiCacheHost}}
elastiCachePort: {{elastiCachePort}}
region: {{region}}
