gitterToken: <token>
gitterRoomId: <roomId>
fromAddress: resumes@<url>
recipients: <string || array of email addresses>
resumesBucket: <bucketName>
applicantsTable: <tableName>
elastiCacheHost: <url>
elastiCachePort: <int>
region: <availabilityRegion>

